// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SetepassosPRJ.Models;

namespace SetepassosPRJ.Migrations
{
    [DbContext(typeof(HiScoresDbContext))]
    partial class HiScoresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SetepassosPRJ.Models.HiScores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Chave");

                    b.Property<int>("GameID");

                    b.Property<int>("MoedasOuroTotal");

                    b.Property<string>("Nome");

                    b.Property<int>("NumFugas");

                    b.Property<int>("NumInimigosDerrotados");

                    b.Property<int>("NumItensEncontrados");

                    b.Property<int>("PocoesObtidas");

                    b.Property<int>("PocoesUsadas");

                    b.Property<int>("ResultadoJogo");

                    b.Property<bool>("Terminado");

                    b.Property<int>("TotalAreasExaminadas");

                    b.HasKey("Id");

                    b.ToTable("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
